### ISSUE TITLE
This plugin uses symfony console, but does not require it so a newer version can be included breaking build processes.

### ISSUE THREAD

**Issue by nlighteneddesign** [silverstripe/recipe-plugin#46] opened 2024-10-17 14:54 UTC
### Module version(s) affected

2.0.1

### Description

As far as I can tell this project expects symfony/console 6 (recipe plugin too)
but there is no dependency, so if you update you get console 7 and a bunch of errors.

### How to reproduce

Include symfony console 7

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## Related issues
- https://github.com/silverstripe/vendor-plugin/issues/82
- https://github.com/silverstripe/.github/issues/325

## PR
- https://github.com/silverstripe/recipe-plugin/pull/47

**Comment by emteknetnz** [comment] 2024-10-23 03:08
Based on [this comment](https://github.com/silverstripe/vendor-plugin/issues/82#issuecomment-2429052619) in the related issue it seems like issue is probably caused by a mis-configured composer.json file at the project file

If this isn't the case and you can point out something wrong at our end then please let me know and I'll reopen this and probably the other issue too

**Comment by GuySartorelli** [comment] 2024-10-23 05:17
This doesn't have anything to do with the composer deps (i.e. composer.json deps) I think. It seems more likely related to what version of `symfony/console` is used _by composer itself_.
The [most recent version of composer](https://github.com/composer/composer/blob/2.8.1/composer.json) has mixed versions in its constraints, which include the version with the strict typehints.

I think we should update this.

**Comment by emteknetnz** [comment] 2024-10-23 21:47
While we could just merge these PRs as they are and they'll work with both versions of symfony via [PHP Covariance](https://www.php.net/manual/en/language.oop5.variance.php), we do have a policy of strictly following semver to make decision making easier. Since there's a method signature change, we'd need to make new majors of recipe-plugin / vendor-plugin and update all CMS 6 modules that depend on them accordingly, if you want to do that then we should backlog a new issue for that

**Comment by GuySartorelli** [comment] 2024-10-23 22:06
I'm not saying we should make this change _in a patch or minor release_.
We can release a major version. That's fine.
I don't see why we'd need a new issue when this issue already explains what's wrong?

**Comment by emteknetnz** [comment] 2024-10-24 00:08
Because we'd basically end up deleting the description of this issue in order to write a new one for doing the work, seems much cleaner to just create a new issue.  I've gone ahead and done this - https://github.com/silverstripe/.github/issues/325

**Comment by GuySartorelli** [comment] 2024-10-24 00:13
That feels unnecessary but seeing as it's already been done:
Closing as a duplicate of https://github.com/silverstripe/recipe-plugin/issues/46

**Closed by GuySartorelli** 2024-10-24 00:13 UTC
Labels: type/api-break
